accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    Home,
    PasswordChange,
    PasswordChangeDone,
)

app_name = 'accounts'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #path('password_change', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDone.as_view(), name='password_change_done'),
]

loginjango/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', Home.as_view(), name='home'),
    path('auth/', include('social_django.urls', namespace='social')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView

from django.urls import reverse_lazy
from django.views.generic import(
    TemplateView,
)


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    # なんかデータ必要だったら
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'password_change.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_name"] = "password_change"
        return context


class PasswordChangeDone(LoginRequiredMixin, PasswordChangeDoneView):
    template_name = 'password_change_done.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="{{ LANGUAGE_CODE|default:"ja-jp" }}">
<head>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <main class="container">
        {% block content %}
            {{ content }}
        {% endblock %}
    </main>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}これから{% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
              <button onclick="location.href='{% url 'accounts:password_change' %}'" class="btn btn-lg btn-primary btn-block text-uppercase"><i class="fab fa-google mr-2"></i>パスワード変更</button>
              <button onclick="location.href='{% url 'accounts:logout' %}'" class="btn btn-lg btn-google btn-block text-uppercase"><i class="fab fa-google mr-2"></i>ログアウト</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}これから{% endblock title %}
{% block content %}
<!-- This snippet uses Font Awesome 5 Free as a dependency. You can download it at fontawesome.io! -->
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <form class="form-signin" method="POST">
            {% csrf_token %}
              <div class="form-label-group">
                <input id="inputusername" name="username" class="form-control" placeholder="Email address" required autofocus>
                <label for="inputusername">メールアドレス</label>
              </div>

              <div class="form-label-group">
                <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <label for="inputPassword">パスワード</label>
              </div>

              <div class="custom-control custom-checkbox mb-3">
                <input type="checkbox" class="custom-control-input" id="customCheck1">
                <label class="custom-control-label" for="customCheck1">Remember password</label>
              </div>
              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Sign in</button>
              <hr class="my-4">
            </form>
          <button onclick="location.href='{% url 'social:begin' 'google-oauth2' %}'" class="btn btn-lg btn-google btn-block text-uppercase"><i class="fab fa-google mr-2"></i> Sign in with Google</button>
          <button class="btn btn-lg btn-facebook btn-block text-uppercase"><i class="fab fa-facebook-f mr-2"></i> Sign in with Facebook</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/password_change.html
{% extends "base.html" %}
{% load static %}
{% block title %}パスワード変更{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">パスワード変更</h5>
            <form id="password_change" class="form-signin" method="POST">
            {% csrf_token %}
              {% for item in form %}
              <div class="form-label-group">
                <input type="{{ item.field.widget.input_type }}" id="{{ item.id_for_label }}" name="{{ item.name }}" class="form-control" placeholder="Password" required autofocus>
                <label for="{{ item.id_for_label }}">{{ item.label_tag }}</label>
              </div>
              {% endfor %}
            </form>
          <hr class="my-4">
          <button onclick="location.href='{% url 'accounts:home' %}'" class="btn btn-lg btn-google btn-block text-uppercase"><i class="fab fa-google mr-2"></i>戻る</button>
          <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" form="password_change">変更</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/password_change_done.html
{% extends "base.html" %}
{% load static %}
{% block title %}パスワード変更完了{% endblock title %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">パスワード変更完了</h5>
            <hr class="my-4">
            <button onclick="location.href='{% url 'accounts:home' %}'" class="btn btn-lg btn-primary btn-block text-uppercase">戻る</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}